# Generated by Django 4.2.5 on 2023-10-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
